# fly.toml app configuration file generated for server-solitary-river-9108 on 2025-03-14T06:29:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-solitary-river-9108'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
